name: Run Python Script Daily

on:
  # 定时触发：使用UTC时间，每天00:00（即北京时间08:00）运行
  schedule:
    - cron: "0 6 * * *" # 分钟 小时 日 月 星期
  # 允许手动触发
  workflow_dispatch:
  
  # 3. 允许通过 GitHub API 触发
  repository_dispatch:
    types: [run-python-script]  # 自定义事件类型名称，可任意命名

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # 指定你需要的Python版本

      - name: Install dependencies
        run: pip install httpx
      - name: Run Python script
        run: python kuake_sign.py
        env:
          AGENTID: ${{ secrets.AGENTID }}
          CORPID: ${{ secrets.CORPID }}
          CORPSECRET: ${{ secrets.CORPSECRET }}
